name: tests-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: shortener
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install deps
        run: npm ci

      - name: wait postgres
        run: |
          for i in {1..20}; do
            pg_isready -h 127.0.0.1 -p 5432 && break
            echo "waiting postgres..."
            sleep 2
          done

      - name: create table
        run: |
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -d shortener -c "CREATE TABLE IF NOT EXISTS urls (code TEXT PRIMARY KEY, url TEXT NOT NULL);"

      - name: debug jest
        run: ls -la node_modules/.bin || true

      - name: run unit tests
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: shortener
          PGPORT: 5432
          BASE_URL: "http://localhost:3000"
        run: npm run test:unit

      - name: run integration tests
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: shortener
          PGPORT: 5432
          BASE_URL: "http://localhost:3000"
        run: npm run test:integration
